name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  tests:
    name: Tests (PHP ${{ matrix.php-version }}, TYPO3 ${{ matrix.typo3-version }}, Composer ${{ matrix.composer-version }} & ${{ matrix.dependencies }} dependencies)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ["8.4"]
        composer-version: ["latest"]
        dependencies: ["lowest", "highest"]
        typo3-version: ["13.4"]
        #exclude:
        #  - php-version: "8.1"
        #    typo3-version: "13.4"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v${{ matrix.composer-version }}
          coverage: pcov

      # Install dependencies
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.dependencies }}
          composer-options: --with=typo3/cms-core:"^${{ matrix.typo3-version }}"

      # Run tests
      - name: Run unit tests
        run: composer test:unit

      # todo: add coverage and reporting
